apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-music-stack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-music-stack
    spec:
      initContainers:
      - name: init-track1
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-MB9-128k.mp3 -o /tmp/mpd/music/Mars64-MB9-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/mpd/music/
          name: mpd-music
        resources:
          requests:
            cpu: 10m
      - name: init-track2
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-MutantBreakz8-Emit-128k.mp3 -o /tmp/mpd/music/Mars64-MutantBreakz8-Emit-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/mpd/music/
          name: mpd-music
        resources:
          requests:
            cpu: 10m
      - name: init-track3
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-Svartifoss-128k.mp3 -o /tmp/mpd/music/Mars64-Svartifoss-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/mpd/music/
          name: mpd-music
        resources:
          requests:
            cpu: 10m
      - name: init-playlists
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64.m3u -o /tmp/mpd/playlists/Mars64.m3u; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/mpd/playlists/
          name: mpd-playlists
        resources:
          requests:
            cpu: 10m
      - name: chown-playlists
        image: busybox
        command: ['/bin/chown', '-R', '100:18', '/tmp/mpd/playlists']
        volumeMounts:
        - mountPath: /tmp/mpd/playlists
          name: mpd-playlists
        resources:
          requests:
            cpu: 10m
      containers:
      - name: icecast
        image: mars64/icecast:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        resources:
          requests:
            cpu: 10m
        env:
        - name: ICECAST_VERSION
          value: "2.4.3-r4"
        - name: ICECAST_LOCATION
          value: "DEEP BASS STATION 9"
        - name: ICECAST_ADMIN
          value: "iceadmin@localhost"
        - name: ICECAST_HOSTNAME
          value: "icecast.mars64.k8s.sofree.us"
      - name: mpd
        image: mars64/mpd:latest
        ports: 
        - containerPort: 6600
        volumeMounts:
        - mountPath: /var/lib/mpd/music
          name: mpd-music
          readOnly: false
        - mountPath: /var/lib/mpd/playlists
          name: mpd-playlists
          readOnly: false
        - mountPath: /var/lib/mpd/database
          name: mpd-db
          readOnly: false
        livenessProbe: 
          exec: 
            command:
              - hostname
        resources:
          requests:
            cpu: 10m
      - name: ympd
        image: mars64/ympd:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet: 
            path: /
            port: 8080
        resources:
          requests:
            cpu: 10m
      - name: sima
        image: mars64/sima:latest
        resources:
          requests:
            cpu: 10m
      volumes: 
      - name: mpd-music
        emptyDir: {}
      - name: mpd-playlists
        emptyDir: {}
      - name: mpd-db
        emptyDir: {}
