---
apiVersion: v1
kind: Service
metadata:
  name: ympd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ympd.$CLUSTERNAME.
spec:
  selector:
    app: k8s-music-stack
  ports:
    - name: ympd
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - <your.public.ip.here>/32
