---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-music-stack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-music-stack
    spec:
      initContainers:
      - name: init-track1
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-MB9-128k.mp3 -o /tmp/icecast/music/Mars64-MB9-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/icecast/music/
          name: mpd-music
      - name: init-track2
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-MutantBreakz8-Emit-128k.mp3 -o /tmp/icecast/music/Mars64-MutantBreakz8-Emit-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/icecast/music/
          name: mpd-music
      - name: init-track3
        image: appropriate/curl
        command: ['sh', '-c', 'until curl --create-dirs -L http://rinseandrepeatradio.com/music/k8s.101/Mars64-Svartifoss-128k.mp3 -o /tmp/icecast/music/Mars64-Svartifoss-128k.mp3; do sleep 2; done;']
        volumeMounts:
        - mountPath: /tmp/icecast/music/
          name: mpd-music
      containers:
      - name: icecast
        image: mars64/icecast:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
      - name: mpd
        image: mars64/mpd:latest
        ports: 
        - containerPort: 6600
        volumeMounts:
        - mountPath: /var/lib/mpd/music
          name: mpd-music
          readOnly: false
        - mountPath: /var/lib/mpd/playlists
          name: mpd-playlists
          readOnly: false
        - mountPath: /var/lib/mpd/database
          name: mpd-db
          readOnly: false
        livenessProbe: 
          exec: 
            command:
              - hostname
      - name: ympd
        image: mars64/ympd:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet: 
            path: /
            port: 8080
      volumes: 
      - name: mpd-music
        emptyDir: {}
      - name: mpd-playlists
        emptyDir: {}
      - name: mpd-db
        emptyDir: {}
