---
apiVersion: v1
kind: Service
metadata:
  name: ympd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ympd.mars64.k8s.sofree.us.
spec:
  selector:
    app: k8s-music-stack
  ports:
    - name: ympd
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 67.176.126.195/32
