---
apiVersion: v1
kind: Service
metadata:
  name: ympd
spec:
  selector:
    app: k8s-music-stack
  ports:
    - name: ympd
      port: 8080
      targetPort: 8080
      nodePort: 31002
  type: NodePort
