---
apiVersion: v1
kind: Service
metadata:
  name: icecast
spec:
  selector:
    app: k8s-music-stack
  ports:
    - name: icecast
      port: 8000
      targetPort: 8000
      nodePort: 31001
  type: NodePort
